name: API Tests
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---- .NET 8 -------------------------------------------------------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore & build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
        working-directory: RestfulBooker.Tests

      - name: Run tests
        run: dotnet test --configuration Release --no-build
        working-directory: RestfulBooker.Tests
